import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import Navbar from "./components/Navbar";
import { NextAuthProvider } from "./components/AuthProvider";

const inter = Montserrat({ subsets: ['cyrillic']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
          {modal}
        </body>
      </html>
    </NextAuthProvider>
  );
}
